### ISSUE TITLE
Extension is not compiled & tested under MacOS

### ISSUE THREAD

**Issue by danolivo** [pierreforstmann/pg_readonly#13]
I tried to sketch the proposal described in the previous issue. But it seems the extension is designed for specific settings. I widened ot a little. Please consider my PRs.

**Comment by pierreforstmann** [comment]
I have merged you PRs but I cannot compile on Alma Linux 9.7 with PG 18.3.
I have:

$ git status
HEAD detached at REL_18_3
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	contrib/pg_readonly/
	src/backend/utils/guc_tables.inc.c
	src/include/utils/guc_tables.inc.c

nothing added to commit but untracked files present (use "git add" to track)


I get:

cc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -fPIC -fvisibility=hidden -I. -I. -I../../src/include -D_GNU_SOURCE      -c -o pg_readonly.o pg_readonly.c
pg_readonly.c: In function ‘pgro_set_readonly_internal’:
pg_readonly.c:115:17: warning: implicit declaration of function ‘SignalRecoveryConflictWithVirtualXID’ [-Wimplicit-function-declaration]
  115 |                 SignalRecoveryConflictWithVirtualXID(
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pg_readonly.c:117:25: error: ‘RECOVERY_CONFLICT_SNAPSHOT’ undeclared (first use in this function); did you mean ‘PROCSIG_RECOVERY_CONFLICT_SNAPSHOT’?
  117 |                         RECOVERY_CONFLICT_SNAPSHOT);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                         PROCSIG_RECOVERY_CONFLICT_SNAPSHOT
pg_readonly.c:117:25: note: each undeclared identifier is reported only once for each function it appears in
make: *** [<builtin>: pg_readonly.o] Error 1
[pierre@alma pg_readonly]$ 

OK, I can compile with current postgres master but this is too early for me.

About MacOS i don't any machine to test.

**Comment by danolivo** [comment]
Let me check ...

**Comment by danolivo** [comment]
Ok, I created a new pull request to fix it - I missed that the rename commit is only one month old ;)
Sorry for the multiple almost empty changes - it seems that my IDE fixes trailing backspaces automatically.

**Comment by pierreforstmann** [comment]
After this PR merge I can now compile without any error or warning.

**Comment by pierreforstmann** [comment]
And `make installcheck `is also OK with REL_18_3 tag.
Thanks.
